[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["canvas"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
